---
version: "2"
services:
  # Guacamole service for Robust Backdoor access
  guac:
    image: db260179/guacamole-combined
    ports:
      - "127.0.0.1:8080:8080/tcp"
    volumes:
      - /Users/mayank/.pref/data/guac:/app/data:rw
    networks:
      mgmt:
    hostname: guac
    mem_limit: 500m
    memswap_limit: 500m
    mem_reservation: 300m

networks: 
  mgmt:
    driver: bridge