---
version: "2"
services:
  # Docker registry service for DIND Backdoor environment
  registry:
    image: registry
    ports:
      - "127.0.0.1:80:80/tcp"
    networks:
      mgmt:
    hostname: registry
networks: 
  mgmt:
    driver: bridge