---
version: "2"
services:
  # Docker registry service for DIND Backdoor environment
  registry.store:
    image: registry:2
    ports:
      - 80:80
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
    volumes:
      - /Users/mayank/.pref/data/registry:/data:rw
    hostname: registry.store
    networks:
      mgmt:
networks: 
  mgmt:
    driver: bridge