---
version: "2"
services:
  # Docker-in-Docker environment for Sandbox
  sandbox:
    build:
      context: ./
      dockerfile: sandbox.dockerfile
    image: backdoor:sandbox
    privileged: true
    ports:
      - "9000-9010:9000-9010/tcp"
    volumes:
      - ~/Documents/Github/:/data
      - ~/Documents/homelab/config:/root/.kube/config
    networks:
      mgmt:
networks: 
  mgmt:
    driver: bridge