---
version: '2'
services:
  web:
    image: uvatbc/docker-ttrss
    ports:
      - "8083:80"
    depends_on:
      - db
    links:
      - db
    environment:
      - TTRSS_DB_HOST=db
      - TTRSS_DB_USER=postgres
      - TTRSS_DB_PASS=Password
    restart: always
  db:
    image: postgres:9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: ttrss
    volumes:
      - $DATA/ttrss:/var/lib/postgresql/data/pgdata