---
version: "2"
services:
  # XenOrchestra for XenServer management 
  xo:
    image: brijohn/xen-orchestra
    ports:
      - "127.0.0.1:8000:8000/tcp"
    volumes:
      - /Users/mayank/.pref/data/xo/redis:/var/lib/redis:rw
      - /Users/mayank/.pref/data/xo/server:/var/lib/xo-server
    networks:
      mgmt:
networks: 
  mgmt:
    driver: bridge